import 'dotenv/config'
import db from './db.js'

const gifts = [
  { id: "gift_001", name: "Patrocine a Lua de Mel dos Noivos", category: "lua-de-mel", price: 13293.08, icon: "fa-plane-departure", sort_order: 1 },
  { id: "gift_002", name: "2 Passagens Aéreas para a Lua de Mel", category: "lua-de-mel", price: 4532.96, icon: "fa-ticket", sort_order: 2 },
  { id: "gift_003", name: "Aluguel de Carro para a Lua de Mel", category: "lua-de-mel", price: 1956.48, icon: "fa-car", sort_order: 3 },
  { id: "gift_004", name: "Passeio Lua de Mel", category: "lua-de-mel", price: 478.14, icon: "fa-umbrella-beach", sort_order: 4 },
  { id: "gift_005", name: "Vale Passeio de Barco", category: "lua-de-mel", price: 365.38, icon: "fa-ship", sort_order: 5 },
  { id: "gift_006", name: "Vale Sessão de Massagem para o Casal", category: "lua-de-mel", price: 451.56, icon: "fa-spa", sort_order: 6 },
  { id: "gift_007", name: "Cota Jantar Romântico para o Casal", category: "lua-de-mel", price: 300.34, icon: "fa-utensils", sort_order: 7 },
  { id: "gift_008", name: "Geladeira Frost Free", category: "eletro", price: 2553.14, icon: "fa-refrigerator", sort_order: 8 },
  { id: "gift_009", name: "Lava-Louças", category: "eletro", price: 3172.13, icon: "fa-sink", sort_order: 9 },
  { id: "gift_010", name: "Lavadora de Roupas", category: "eletro", price: 2433.40, icon: "fa-soap", sort_order: 10 },
  { id: "gift_011", name: "Fogão de Piso 5 Bocas", category: "eletro", price: 2286.63, icon: "fa-fire-burner", sort_order: 11 },
  { id: "gift_012", name: "Ar-Condicionado Split Springer", category: "eletro", price: 1956.48, icon: "fa-wind", sort_order: 12 },
  { id: "gift_013", name: "Robô Aspirador de Pó", category: "eletro", price: 1213.97, icon: "fa-robot", sort_order: 13 },
  { id: "gift_014", name: "Smart TV 50\" UHD 4K", category: "eletro", price: 2806.27, icon: "fa-tv", sort_order: 14 },
  { id: "gift_015", name: "Coifa de Parede", category: "eletro", price: 909.01, icon: "fa-fan", sort_order: 15 },
  { id: "gift_016", name: "Forno Micro-ondas", category: "eletro", price: 733.02, icon: "fa-cookie", sort_order: 16 },
  { id: "gift_017", name: "Centrífuga de Frutas", category: "eletro", price: 577.53, icon: "fa-blender", sort_order: 17 },
  { id: "gift_018", name: "Purificador de Água", category: "eletro", price: 523.07, icon: "fa-glass-water", sort_order: 18 },
  { id: "gift_019", name: "Batedeira Planetária", category: "eletro", price: 511.23, icon: "fa-blender-phone", sort_order: 19 },
  { id: "gift_020", name: "Fritadeira Airfryer", category: "eletro", price: 478.25, icon: "fa-fire", sort_order: 20 },
  { id: "gift_021", name: "Panela Elétrica", category: "eletro", price: 447.26, icon: "fa-bowl-food", sort_order: 21 },
  { id: "gift_022", name: "Panela Elétrica para Arroz", category: "eletro", price: 280.53, icon: "fa-bowl-rice", sort_order: 22 },
  { id: "gift_023", name: "Liquidificador", category: "eletro", price: 313.60, icon: "fa-blender", sort_order: 23 },
  { id: "gift_024", name: "Cafeteira Elétrica", category: "eletro", price: 290.94, icon: "fa-coffee", sort_order: 24 },
  { id: "gift_025", name: "Cafeteira Italiana", category: "eletro", price: 102.55, icon: "fa-mug-hot", sort_order: 25 },
  { id: "gift_026", name: "Mixer", category: "eletro", price: 284.89, icon: "fa-blender", sort_order: 26 },
  { id: "gift_027", name: "Aspirador de Pó Vertical", category: "eletro", price: 275.03, icon: "fa-vacuum", sort_order: 27 },
  { id: "gift_028", name: "Pipoqueira Elétrica sem Óleo", category: "eletro", price: 260.57, icon: "fa-popcorn", sort_order: 28 },
  { id: "gift_029", name: "Torradeira", category: "eletro", price: 178.60, icon: "fa-bread-slice", sort_order: 29 },
  { id: "gift_030", name: "Sanduicheira Grill", category: "eletro", price: 167.75, icon: "fa-cheese", sort_order: 30 },
  { id: "gift_031", name: "Chaleira Elétrica", category: "eletro", price: 166.55, icon: "fa-teapot", sort_order: 31 },
  { id: "gift_032", name: "Ferro de Passar a Vapor", category: "eletro", price: 108.25, icon: "fa-shirt", sort_order: 32 },
  { id: "gift_033", name: "Sofá Estofado 3 Lugares", category: "moveis", price: 3348.70, icon: "fa-couch", sort_order: 33 },
  { id: "gift_034", name: "Conjunto para Sala de Jantar", category: "moveis", price: 2156.84, icon: "fa-table", sort_order: 34 },
  { id: "gift_035", name: "Rack TV", category: "moveis", price: 787.51, icon: "fa-tv", sort_order: 35 },
  { id: "gift_036", name: "Cômoda Colúmbia", category: "moveis", price: 696.86, icon: "fa-box", sort_order: 36 },
  { id: "gift_037", name: "Escrivaninha Branca com Gaveta", category: "moveis", price: 569.57, icon: "fa-desktop", sort_order: 37 },
  { id: "gift_038", name: "Buffet de Sala", category: "moveis", price: 527.62, icon: "fa-store", sort_order: 38 },
  { id: "gift_039", name: "Baú em Madeira", category: "moveis", price: 499.11, icon: "fa-archive", sort_order: 39 },
  { id: "gift_040", name: "Aparador", category: "moveis", price: 408.73, icon: "fa-table", sort_order: 40 },
  { id: "gift_041", name: "Estante", category: "moveis", price: 285.75, icon: "fa-book-open", sort_order: 41 },
  { id: "gift_042", name: "Mesa de Centro Retangular Retrô", category: "moveis", price: 240.68, icon: "fa-table", sort_order: 42 },
  { id: "gift_043", name: "Sapateira Compacta", category: "moveis", price: 203.98, icon: "fa-shoe-prints", sort_order: 43 },
  { id: "gift_044", name: "Puff", category: "moveis", price: 187.33, icon: "fa-chair", sort_order: 44 },
  { id: "gift_045", name: "Conjunto de Mesas Laterais", category: "moveis", price: 510.65, icon: "fa-table-cells", sort_order: 45 },
  { id: "gift_046", name: "Abajur", category: "moveis", price: 96.98, icon: "fa-lightbulb", sort_order: 46 },
  { id: "gift_047", name: "Relógio de Parede", category: "moveis", price: 119.74, icon: "fa-clock", sort_order: 47 },
  { id: "gift_048", name: "Espelho Redondo com Alça", category: "moveis", price: 102.29, icon: "fa-circle", sort_order: 48 },
  { id: "gift_049", name: "Conjunto de Quadros", category: "moveis", price: 205.56, icon: "fa-image", sort_order: 49 },
  { id: "gift_050", name: "Porta-Retrato", category: "moveis", price: 141.23, icon: "fa-camera", sort_order: 50 },
  { id: "gift_051", name: "Vaso Grande", category: "moveis", price: 131.11, icon: "fa-prescription-bottle", sort_order: 51 },
  { id: "gift_052", name: "Manta", category: "moveis", price: 109.56, icon: "fa-blanket", sort_order: 52 },
  { id: "gift_053", name: "Tapete", category: "moveis", price: 261.77, icon: "fa-scroll", sort_order: 53 },
  { id: "gift_054", name: "Tapete de Banheiro", category: "moveis", price: 82.17, icon: "fa-bath", sort_order: 54 },
  { id: "gift_055", name: "Caminho de Mesa", category: "moveis", price: 95.43, icon: "fa-lines-leaning", sort_order: 55 },
  { id: "gift_056", name: "Conjunto de Almofadas", category: "moveis", price: 260.57, icon: "fa-heart", sort_order: 56 },
  { id: "gift_057", name: "Aparelho de Jantar - 30 Peças", category: "cozinha", price: 791.00, icon: "fa-plate-wheat", sort_order: 57 },
  { id: "gift_058", name: "Conjunto de Panelas", category: "cozinha", price: 786.71, icon: "fa-kitchen-set", sort_order: 58 },
  { id: "gift_059", name: "Utensílios de Cozinha", category: "cozinha", price: 253.94, icon: "fa-spoon", sort_order: 59 },
  { id: "gift_060", name: "Conjunto de Assadeiras", category: "cozinha", price: 363.83, icon: "fa-layer-group", sort_order: 60 },
  { id: "gift_061", name: "Conjunto de Formas", category: "cozinha", price: 103.98, icon: "fa-cookie-bite", sort_order: 61 },
  { id: "gift_062", name: "Conjunto de Facas", category: "cozinha", price: 181.89, icon: "fa-knife", sort_order: 62 },
  { id: "gift_063", name: "Faqueiro - 42 Peças", category: "cozinha", price: 408.53, icon: "fa-cutlery", sort_order: 63 },
  { id: "gift_064", name: "Frigideira Antiaderente", category: "cozinha", price: 139.91, icon: "fa-square", sort_order: 64 },
  { id: "gift_065", name: "Escorredor de Pratos Arthi Fantastik", category: "cozinha", price: 96.63, icon: "fa-bars", sort_order: 65 },
  { id: "gift_066", name: "Tábua de Cortar", category: "cozinha", price: 61.90, icon: "fa-square", sort_order: 66 },
  { id: "gift_067", name: "Amassador de Alho", category: "cozinha", price: 58.51, icon: "fa-compress", sort_order: 67 },
  { id: "gift_068", name: "Colher de Pau", category: "cozinha", price: 77.35, icon: "fa-spoon", sort_order: 68 },
  { id: "gift_069", name: "Cortador de Pizza", category: "cozinha", price: 44.16, icon: "fa-pizza-slice", sort_order: 69 },
  { id: "gift_070", name: "Moedor de Pimenta", category: "cozinha", price: 78.77, icon: "fa-pepper-hot", sort_order: 70 },
  { id: "gift_071", name: "Conjunto de Bowls", category: "cozinha", price: 152.33, icon: "fa-bowl-food", sort_order: 71 },
  { id: "gift_072", name: "Saladeira", category: "cozinha", price: 106.82, icon: "fa-carrot", sort_order: 72 },
  { id: "gift_073", name: "Cesta para Pães", category: "cozinha", price: 49.19, icon: "fa-basket-shopping", sort_order: 73 },
  { id: "gift_074", name: "Açucareiro", category: "cozinha", price: 48.29, icon: "fa-cubes", sort_order: 74 },
  { id: "gift_075", name: "Manteigueira Branca", category: "cozinha", price: 86.09, icon: "fa-cheese", sort_order: 75 },
  { id: "gift_076", name: "Balde de Gelo", category: "cozinha", price: 211.50, icon: "fa-bucket", sort_order: 76 },
  { id: "gift_077", name: "Bandeja", category: "cozinha", price: 92.75, icon: "fa-tray", sort_order: 77 },
  { id: "gift_078", name: "Bandeja para Sofá", category: "cozinha", price: 72.53, icon: "fa-tray", sort_order: 78 },
  { id: "gift_079", name: "Bandeja de Prata para Lavabo", category: "cozinha", price: 104.35, icon: "fa-square", sort_order: 79 },
  { id: "gift_080", name: "Jarra de Cristal Bohemia", category: "cozinha", price: 86.35, icon: "fa-wine-glass", sort_order: 80 },
  { id: "gift_081", name: "Decanter de Vidro", category: "cozinha", price: 96.96, icon: "fa-wine-bottle", sort_order: 81 },
  { id: "gift_082", name: "Garrafa Térmica", category: "cozinha", price: 90.15, icon: "fa-bottle-water", sort_order: 82 },
  { id: "gift_083", name: "Jogo de Copos", category: "cozinha", price: 108.47, icon: "fa-glass-water", sort_order: 83 },
  { id: "gift_084", name: "Jogo de Copos Medidores", category: "cozinha", price: 80.96, icon: "fa-fill-drip", sort_order: 84 },
  { id: "gift_085", name: "Jogo de Taças de Vinho", category: "cozinha", price: 154.45, icon: "fa-glass-water-droplet", sort_order: 85 },
  { id: "gift_086", name: "Jogo de Taças para Sobremesa", category: "cozinha", price: 165.84, icon: "fa-ice-cream", sort_order: 86 },
  { id: "gift_087", name: "Conjunto de Xícaras para Chá", category: "cozinha", price: 245.98, icon: "fa-mug-hot", sort_order: 87 },
  { id: "gift_088", name: "Jogo de Xícaras para Café com Pires", category: "cozinha", price: 137.66, icon: "fa-coffee", sort_order: 88 },
  { id: "gift_089", name: "Conjunto Porta Condimentos Giratório", category: "cozinha", price: 300.34, icon: "fa-spinner", sort_order: 89 },
  { id: "gift_090", name: "Porta Condimentos Giratório em Madeira", category: "cozinha", price: 220.79, icon: "fa-tree", sort_order: 90 },
  { id: "gift_091", name: "Conjunto de Potes Herméticos Redondos", category: "cozinha", price: 117.37, icon: "fa-jar", sort_order: 91 },
  { id: "gift_092", name: "Jogo de Lençol Casal", category: "quarto-banho", price: 283.80, icon: "fa-bed", sort_order: 92 },
  { id: "gift_093", name: "Edredom", category: "quarto-banho", price: 383.46, icon: "fa-blanket", sort_order: 93 },
  { id: "gift_094", name: "2 Roupões Grego", category: "quarto-banho", price: 350.64, icon: "fa-user-tie", sort_order: 94 },
  { id: "gift_095", name: "2 Travesseiros", category: "quarto-banho", price: 205.99, icon: "fa-pillow", sort_order: 95 },
  { id: "gift_096", name: "Jogo de Toalha de Banho", category: "quarto-banho", price: 153.17, icon: "fa-toilet-paper", sort_order: 96 },
  { id: "gift_097", name: "Jogo de Banho Gigante Karsten Lumina (5 Pçs)", category: "quarto-banho", price: 337.49, icon: "fa-bath", sort_order: 97 },
  { id: "gift_098", name: "Kit Banheiro", category: "quarto-banho", price: 100.25, icon: "fa-pump-soap", sort_order: 98 },
  { id: "gift_099", name: "Lixeira Inox 3 Litros", category: "quarto-banho", price: 109.15, icon: "fa-trash", sort_order: 99 },
  { id: "gift_100", name: "Cesto para Roupas", category: "quarto-banho", price: 107.48, icon: "fa-basket-shopping", sort_order: 100 },
  { id: "gift_101", name: "Carrinho Gourmet para Churrasco", category: "gourmet", price: 447.37, icon: "fa-drumstick-bite", sort_order: 101 },
  { id: "gift_102", name: "Cartão Presente Bronze", category: "cartao", price: 82.17, icon: "fa-gift", sort_order: 102 },
  { id: "gift_103", name: "Cartão Presente Prata", category: "cartao", price: 142.44, icon: "fa-gift", sort_order: 103 },
  { id: "gift_104", name: "Cartão Presente Ouro", category: "cartao", price: 202.71, icon: "fa-gift", sort_order: 104 },
]

const insert = db.prepare(`
  INSERT OR IGNORE INTO gifts (id, name, category, price, icon, sort_order)
  VALUES (@id, @name, @category, @price, @icon, @sort_order)
`)

const insertMany = db.transaction((items) => {
  for (const item of items) insert.run(item)
})

insertMany(gifts)

const { count } = db.prepare('SELECT COUNT(*) AS count FROM gifts').get()
console.log(`✅ Seed concluído — ${count} presentes na tabela.`)
